theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 プロフィール.com"

baseURL = "https://xn--dck5ef6fh6g.com/misora/"
title = "みそら | プロフィール.com"

[params]
author = "みそら"
icon = "misora"
description = "zzz"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/intent/user?user_id=1631351854377623552"
